### ISSUE TITLE
Overcomplication on removal of S19 CTRL board cover

### ISSUE THREAD

**Issue by UpstreamData** [econoalchemist/UpstreamData-Startup#1]
In the file for "Preliminary Checks", there is a section with  - 
"On the Antminer, remove the two small screws on both ends of the larger electrical cover. Lift the larger electrical cover off the Antminer and ensure the wire harness connections are all tight and seated on the circuit board, the bus bars are tight and not touching each other, and that the hashboard connections are seated and tight."

This overcomplicates the removal of the cover.  Only the small screw underneath the silver button needs to be loosened (as shown below), then the cover will comer right off by pressing it inwards and lifting the cover.
![Antminer-S19-Pro-110TH-5](https://user-images.githubusercontent.com/75442874/152851953-e88b5932-017b-4cd2-940f-8e06d634a8df.jpg)

**Comment by econoalchemist** [comment]
ACK. That makes it way easier. Will update the guide.

**Comment by econoalchemist** [comment]
This should be fixed with [this commit](https://github.com/econoalchemist/UpstreamData-Startup/commit/e9edec8bc318d2b8ce363578da95a4788310fae9).

If you agree, I'll close this issue out.
